version: "3.8"

services:
  app:
    build:
      context: .
      target: prod
    container_name: nuxt_app
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    container_name: nuxt_nginx
    environment:
      - TZ=Europe/Moscow
      - NGINX_HOST=localhost
      - ROOT_DIRECTORY=/
    depends_on:
      - app
    command: >
      /bin/sh -c "export NGINX_HOST; export ROOT_DIRECTORY;
      envsubst '$$NGINX_HOST,$$ROOT_DIRECTORY' < /nginx.template > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
    volumes:
      - ./nginx/development.template:/nginx.template
    ports:
      - "80:80"
